export const SET_LOGIN_PROP = 'SET_LOGIN_PROP';
export const SET_NAV_PROP = 'SET_NAV_PROP';
export const SET_PROFILE_PROP = 'SET_PROFILE_PROP';
export const SET_APP_PROP = 'SET_APP_PROP';
export const SET_OVERLAY_PROP = 'SET_OVERLAY_PROP';
export const SET_OVERLAY_PROPS = 'SET_OVERLAY_PROPS';
export const CLEAR_OVERLAY_PROPS = 'CLEAR_OVERLAY_PROPS';
export const SET_COMPANY_PROP = 'SET_COMPANY_PROP';
